### ISSUE TITLE
Fails with Terraform v0.8.8

### ISSUE THREAD

**Issue by daemonza** [rgl/terraform-provider-vultr#9]
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 4, Ours: 2

**Comment by rtizzy** [comment]
Howdy @daemonza. I recently fixed this issue myself. 

I opened a related issue on Terraform's Git. The confusion is due to the fact that Terraforms output is incredibly unclear. That error actually means the Plugins version is 2 and terraforms API version is 4. 

See [Terraform issue](https://github.com/hashicorp/terraform/issues/12580)

Here is how to correctly compile. 

After performing the following commands 

```
go get github.com/hashicorp/terraform
go get github.com/JamesClonk/vultr
```

Run these commands:

```
cd src/github.com/hashicorp/terraform
git checkout v0.8.8
```
Then perform the rest of the instructions as outlined in the Readme

From what I can tell, the original developer is no longer maintaining this plugin so I will likely be forking it shortly. I tried reaching out on Twitter with no answer and it would appear he has not answered any issues for quite awhile.

**Comment by rtizzy** [comment]
I have forked the repository here and have updated instructions on building. I'm also going to work on merging the open pull request for host name and tag support. 

https://github.com/elricsfate/terraform-provider-vultr

**Comment by rtizzy** [comment]
I have now tested and merged the support for the optional hostname and tag variables, updated the readme, and uploaded a release for those who do not wish to deal with compilation.

**Comment by daemonza** [comment]
awesome thanks @elricsfate just tried it on your repo and it's working!
